import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";

type Build = {
  id: string;
  created_at: string;
  title: string;
  prompt: string;
  model: string | null;
  client_id: string | null;
  byte_size: number;
};

export const Route = createFileRoute("/gallery")({
  head: () => ({
    meta: [
      { title: "Vibe Coder Gallery — every build, every browser" },
      { name: "description", content: "Every page generated by the Vibe Coder, saved automatically across browsers and IPs." },
    ],
  }),
  component: Gallery,
  errorComponent: ({ error, reset }) => (
    <div style={{ padding: 32, color: "#f2eee7", background: "#111317", minHeight: "100vh" }}>
      <h1>Couldn't load gallery</h1>
      <p style={{ color: "#B6BCC8" }}>{error.message}</p>
      <button onClick={reset}>Try again</button>
    </div>
  ),
  notFoundComponent: () => <div style={{ padding: 32 }}>Not found</div>,
});

function Gallery() {
  const [builds, setBuilds] = useState<Build[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [q, setQ] = useState("");

  useEffect(() => {
    fetch("/api/public/builds")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((d) => setBuilds(d.builds as Build[]))
      .catch((e) => setError(e.message));
  }, []);

  const filtered = (builds ?? []).filter((b) => {
    if (!q) return true;
    const s = q.toLowerCase();
    return b.title.toLowerCase().includes(s) || b.prompt.toLowerCase().includes(s);
  });

  return (
    <div style={{ minHeight: "100vh", background: "#111317", color: "#f2eee7", fontFamily: "Inter, system-ui" }}>
      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "20px 28px", borderBottom: "1px solid #22262d" }}>
        <div>
          <h1 style={{ fontFamily: "Fraunces, Georgia, serif", fontSize: 28, margin: 0, color: "#F4A125" }}>Build Gallery</h1>
          <p style={{ color: "#B6BCC8", margin: "4px 0 0", fontSize: 13 }}>
            {builds ? `${builds.length} builds saved across all browsers` : "Loading…"}
          </p>
        </div>
        <Link to="/" style={{ color: "#F4A125", textDecoration: "none", fontSize: 14 }}>← Back to Coder</Link>
      </header>

      <div style={{ padding: "20px 28px" }}>
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="Search builds…"
          style={{ width: "100%", maxWidth: 480, padding: "10px 14px", background: "#0b0d10", color: "#f2eee7", border: "1px solid #22262d", borderRadius: 8, fontFamily: "inherit" }}
        />
      </div>

      {error && <div style={{ padding: "0 28px", color: "#ff8a8a" }}>{error}</div>}

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 16, padding: "8px 28px 40px" }}>
        {filtered.map((b) => (
          <a
            key={b.id}
            href={`/api/public/builds/${b.id}`}
            target="_blank"
            rel="noreferrer"
            style={{ display: "block", background: "#171a20", border: "1px solid #22262d", borderRadius: 12, overflow: "hidden", textDecoration: "none", color: "inherit" }}
          >
            <iframe
              src={`/api/public/builds/${b.id}`}
              title={b.title}
              sandbox=""
              style={{ width: "100%", height: 180, border: 0, background: "#0b0d10", pointerEvents: "none" }}
              loading="lazy"
            />
            <div style={{ padding: 14 }}>
              <div style={{ fontFamily: "Fraunces, Georgia, serif", fontSize: 16, color: "#F4A125", marginBottom: 4 }}>{b.title}</div>
              <div style={{ fontSize: 12, color: "#B6BCC8", display: "flex", justifyContent: "space-between", gap: 8 }}>
                <span>{new Date(b.created_at).toLocaleString()}</span>
                <span>{(b.byte_size / 1024).toFixed(1)} KB</span>
              </div>
              {b.prompt && (
                <div style={{ fontSize: 12, color: "#8a919b", marginTop: 8, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>
                  {b.prompt}
                </div>
              )}
            </div>
          </a>
        ))}
        {builds && filtered.length === 0 && (
          <div style={{ color: "#B6BCC8", padding: 20 }}>No builds yet. Go make something.</div>
        )}
      </div>
    </div>
  );
}
