/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntrosIndexRouteImport } from './routes/intros/index'
import { Route as IntrosRequestsRouteImport } from './routes/intros/requests'
import { Route as IntrosProfileRouteImport } from './routes/intros/profile'
import { Route as IntrosPreferencesRouteImport } from './routes/intros/preferences'
import { Route as IntrosPeopleRouteImport } from './routes/intros/people'
import { Route as IntrosMessagesRouteImport } from './routes/intros/messages'
import { Route as IntrosMemoryRouteImport } from './routes/intros/memory'
import { Route as IntrosInsightsRouteImport } from './routes/intros/insights'
import { Route as IntrosElenaRossiRouteImport } from './routes/intros/elena-rossi'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosIndexRoute = IntrosIndexRouteImport.update({
  id: '/intros/',
  path: '/intros/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosRequestsRoute = IntrosRequestsRouteImport.update({
  id: '/intros/requests',
  path: '/intros/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosProfileRoute = IntrosProfileRouteImport.update({
  id: '/intros/profile',
  path: '/intros/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosPreferencesRoute = IntrosPreferencesRouteImport.update({
  id: '/intros/preferences',
  path: '/intros/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosPeopleRoute = IntrosPeopleRouteImport.update({
  id: '/intros/people',
  path: '/intros/people',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosMessagesRoute = IntrosMessagesRouteImport.update({
  id: '/intros/messages',
  path: '/intros/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosMemoryRoute = IntrosMemoryRouteImport.update({
  id: '/intros/memory',
  path: '/intros/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosInsightsRoute = IntrosInsightsRouteImport.update({
  id: '/intros/insights',
  path: '/intros/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrosElenaRossiRoute = IntrosElenaRossiRouteImport.update({
  id: '/intros/elena-rossi',
  path: '/intros/elena-rossi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/intros/elena-rossi': typeof IntrosElenaRossiRoute
  '/intros/insights': typeof IntrosInsightsRoute
  '/intros/memory': typeof IntrosMemoryRoute
  '/intros/messages': typeof IntrosMessagesRoute
  '/intros/people': typeof IntrosPeopleRoute
  '/intros/preferences': typeof IntrosPreferencesRoute
  '/intros/profile': typeof IntrosProfileRoute
  '/intros/requests': typeof IntrosRequestsRoute
  '/intros/': typeof IntrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/intros/elena-rossi': typeof IntrosElenaRossiRoute
  '/intros/insights': typeof IntrosInsightsRoute
  '/intros/memory': typeof IntrosMemoryRoute
  '/intros/messages': typeof IntrosMessagesRoute
  '/intros/people': typeof IntrosPeopleRoute
  '/intros/preferences': typeof IntrosPreferencesRoute
  '/intros/profile': typeof IntrosProfileRoute
  '/intros/requests': typeof IntrosRequestsRoute
  '/intros': typeof IntrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/intros/elena-rossi': typeof IntrosElenaRossiRoute
  '/intros/insights': typeof IntrosInsightsRoute
  '/intros/memory': typeof IntrosMemoryRoute
  '/intros/messages': typeof IntrosMessagesRoute
  '/intros/people': typeof IntrosPeopleRoute
  '/intros/preferences': typeof IntrosPreferencesRoute
  '/intros/profile': typeof IntrosProfileRoute
  '/intros/requests': typeof IntrosRequestsRoute
  '/intros/': typeof IntrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/intros/elena-rossi'
    | '/intros/insights'
    | '/intros/memory'
    | '/intros/messages'
    | '/intros/people'
    | '/intros/preferences'
    | '/intros/profile'
    | '/intros/requests'
    | '/intros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/intros/elena-rossi'
    | '/intros/insights'
    | '/intros/memory'
    | '/intros/messages'
    | '/intros/people'
    | '/intros/preferences'
    | '/intros/profile'
    | '/intros/requests'
    | '/intros'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/intros/elena-rossi'
    | '/intros/insights'
    | '/intros/memory'
    | '/intros/messages'
    | '/intros/people'
    | '/intros/preferences'
    | '/intros/profile'
    | '/intros/requests'
    | '/intros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IntrosElenaRossiRoute: typeof IntrosElenaRossiRoute
  IntrosInsightsRoute: typeof IntrosInsightsRoute
  IntrosMemoryRoute: typeof IntrosMemoryRoute
  IntrosMessagesRoute: typeof IntrosMessagesRoute
  IntrosPeopleRoute: typeof IntrosPeopleRoute
  IntrosPreferencesRoute: typeof IntrosPreferencesRoute
  IntrosProfileRoute: typeof IntrosProfileRoute
  IntrosRequestsRoute: typeof IntrosRequestsRoute
  IntrosIndexRoute: typeof IntrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/': {
      id: '/intros/'
      path: '/intros'
      fullPath: '/intros/'
      preLoaderRoute: typeof IntrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/requests': {
      id: '/intros/requests'
      path: '/intros/requests'
      fullPath: '/intros/requests'
      preLoaderRoute: typeof IntrosRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/profile': {
      id: '/intros/profile'
      path: '/intros/profile'
      fullPath: '/intros/profile'
      preLoaderRoute: typeof IntrosProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/preferences': {
      id: '/intros/preferences'
      path: '/intros/preferences'
      fullPath: '/intros/preferences'
      preLoaderRoute: typeof IntrosPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/people': {
      id: '/intros/people'
      path: '/intros/people'
      fullPath: '/intros/people'
      preLoaderRoute: typeof IntrosPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/messages': {
      id: '/intros/messages'
      path: '/intros/messages'
      fullPath: '/intros/messages'
      preLoaderRoute: typeof IntrosMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/memory': {
      id: '/intros/memory'
      path: '/intros/memory'
      fullPath: '/intros/memory'
      preLoaderRoute: typeof IntrosMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/insights': {
      id: '/intros/insights'
      path: '/intros/insights'
      fullPath: '/intros/insights'
      preLoaderRoute: typeof IntrosInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intros/elena-rossi': {
      id: '/intros/elena-rossi'
      path: '/intros/elena-rossi'
      fullPath: '/intros/elena-rossi'
      preLoaderRoute: typeof IntrosElenaRossiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IntrosElenaRossiRoute: IntrosElenaRossiRoute,
  IntrosInsightsRoute: IntrosInsightsRoute,
  IntrosMemoryRoute: IntrosMemoryRoute,
  IntrosMessagesRoute: IntrosMessagesRoute,
  IntrosPeopleRoute: IntrosPeopleRoute,
  IntrosPreferencesRoute: IntrosPreferencesRoute,
  IntrosProfileRoute: IntrosProfileRoute,
  IntrosRequestsRoute: IntrosRequestsRoute,
  IntrosIndexRoute: IntrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
