/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPatchRouteImport } from './routes/api/patch'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGithubRouteImport } from './routes/api/github'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiPublicSelfTestRouteImport } from './routes/api/public/self-test'
import { Route as ApiPublicEntitlementRouteImport } from './routes/api/public/entitlement'
import { Route as ApiPublicBuildsRouteImport } from './routes/api/public/builds'
import { Route as ApiPublicShareSlugRouteImport } from './routes/api/public/share.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicLibraryCodeRouteImport } from './routes/api/public/library.$code'
import { Route as ApiPublicBuildsIdRouteImport } from './routes/api/public/builds.$id'
import { Route as ApiPublicLibraryCodeIdRouteImport } from './routes/api/public/library.$code.$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatchRoute = ApiPatchRouteImport.update({
  id: '/api/patch',
  path: '/api/patch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSelfTestRoute = ApiPublicSelfTestRouteImport.update({
  id: '/api/public/self-test',
  path: '/api/public/self-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEntitlementRoute = ApiPublicEntitlementRouteImport.update({
  id: '/api/public/entitlement',
  path: '/api/public/entitlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildsRoute = ApiPublicBuildsRouteImport.update({
  id: '/api/public/builds',
  path: '/api/public/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareSlugRoute = ApiPublicShareSlugRouteImport.update({
  id: '/api/public/share/$slug',
  path: '/api/public/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLibraryCodeRoute = ApiPublicLibraryCodeRouteImport.update({
  id: '/api/public/library/$code',
  path: '/api/public/library/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildsIdRoute = ApiPublicBuildsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicBuildsRoute,
} as any)
const ApiPublicLibraryCodeIdRoute = ApiPublicLibraryCodeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicLibraryCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/github': typeof ApiGithubRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/entitlement': typeof ApiPublicEntitlementRoute
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
  '/api/public/library/$code': typeof ApiPublicLibraryCodeRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
  '/api/public/library/$code/$id': typeof ApiPublicLibraryCodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/github': typeof ApiGithubRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/entitlement': typeof ApiPublicEntitlementRoute
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
  '/api/public/library/$code': typeof ApiPublicLibraryCodeRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
  '/api/public/library/$code/$id': typeof ApiPublicLibraryCodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/github': typeof ApiGithubRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/entitlement': typeof ApiPublicEntitlementRoute
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
  '/api/public/library/$code': typeof ApiPublicLibraryCodeRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
  '/api/public/library/$code/$id': typeof ApiPublicLibraryCodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gallery'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/api/generate'
    | '/api/github'
    | '/api/health'
    | '/api/patch'
    | '/checkout/return'
    | '/api/public/builds'
    | '/api/public/entitlement'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
    | '/api/public/library/$code'
    | '/api/public/payments/webhook'
    | '/api/public/share/$slug'
    | '/api/public/library/$code/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gallery'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/api/generate'
    | '/api/github'
    | '/api/health'
    | '/api/patch'
    | '/checkout/return'
    | '/api/public/builds'
    | '/api/public/entitlement'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
    | '/api/public/library/$code'
    | '/api/public/payments/webhook'
    | '/api/public/share/$slug'
    | '/api/public/library/$code/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/gallery'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/api/generate'
    | '/api/github'
    | '/api/health'
    | '/api/patch'
    | '/checkout/return'
    | '/api/public/builds'
    | '/api/public/entitlement'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
    | '/api/public/library/$code'
    | '/api/public/payments/webhook'
    | '/api/public/share/$slug'
    | '/api/public/library/$code/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnlockRoute: typeof UnlockRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiGithubRoute: typeof ApiGithubRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPatchRoute: typeof ApiPatchRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicBuildsRoute: typeof ApiPublicBuildsRouteWithChildren
  ApiPublicEntitlementRoute: typeof ApiPublicEntitlementRoute
  ApiPublicSelfTestRoute: typeof ApiPublicSelfTestRoute
  ApiPublicLibraryCodeRoute: typeof ApiPublicLibraryCodeRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicShareSlugRoute: typeof ApiPublicShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patch': {
      id: '/api/patch'
      path: '/api/patch'
      fullPath: '/api/patch'
      preLoaderRoute: typeof ApiPatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/self-test': {
      id: '/api/public/self-test'
      path: '/api/public/self-test'
      fullPath: '/api/public/self-test'
      preLoaderRoute: typeof ApiPublicSelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/entitlement': {
      id: '/api/public/entitlement'
      path: '/api/public/entitlement'
      fullPath: '/api/public/entitlement'
      preLoaderRoute: typeof ApiPublicEntitlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builds': {
      id: '/api/public/builds'
      path: '/api/public/builds'
      fullPath: '/api/public/builds'
      preLoaderRoute: typeof ApiPublicBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share/$slug': {
      id: '/api/public/share/$slug'
      path: '/api/public/share/$slug'
      fullPath: '/api/public/share/$slug'
      preLoaderRoute: typeof ApiPublicShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/library/$code': {
      id: '/api/public/library/$code'
      path: '/api/public/library/$code'
      fullPath: '/api/public/library/$code'
      preLoaderRoute: typeof ApiPublicLibraryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builds/$id': {
      id: '/api/public/builds/$id'
      path: '/$id'
      fullPath: '/api/public/builds/$id'
      preLoaderRoute: typeof ApiPublicBuildsIdRouteImport
      parentRoute: typeof ApiPublicBuildsRoute
    }
    '/api/public/library/$code/$id': {
      id: '/api/public/library/$code/$id'
      path: '/$id'
      fullPath: '/api/public/library/$code/$id'
      preLoaderRoute: typeof ApiPublicLibraryCodeIdRouteImport
      parentRoute: typeof ApiPublicLibraryCodeRoute
    }
  }
}

interface ApiPublicBuildsRouteChildren {
  ApiPublicBuildsIdRoute: typeof ApiPublicBuildsIdRoute
}

const ApiPublicBuildsRouteChildren: ApiPublicBuildsRouteChildren = {
  ApiPublicBuildsIdRoute: ApiPublicBuildsIdRoute,
}

const ApiPublicBuildsRouteWithChildren = ApiPublicBuildsRoute._addFileChildren(
  ApiPublicBuildsRouteChildren,
)

interface ApiPublicLibraryCodeRouteChildren {
  ApiPublicLibraryCodeIdRoute: typeof ApiPublicLibraryCodeIdRoute
}

const ApiPublicLibraryCodeRouteChildren: ApiPublicLibraryCodeRouteChildren = {
  ApiPublicLibraryCodeIdRoute: ApiPublicLibraryCodeIdRoute,
}

const ApiPublicLibraryCodeRouteWithChildren =
  ApiPublicLibraryCodeRoute._addFileChildren(ApiPublicLibraryCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnlockRoute: UnlockRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiGithubRoute: ApiGithubRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPatchRoute: ApiPatchRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicBuildsRoute: ApiPublicBuildsRouteWithChildren,
  ApiPublicEntitlementRoute: ApiPublicEntitlementRoute,
  ApiPublicSelfTestRoute: ApiPublicSelfTestRoute,
  ApiPublicLibraryCodeRoute: ApiPublicLibraryCodeRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicShareSlugRoute: ApiPublicShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
