/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPatchRouteImport } from './routes/api/patch'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiPublicSelfTestRouteImport } from './routes/api/public/self-test'
import { Route as ApiPublicBuildsRouteImport } from './routes/api/public/builds'
import { Route as ApiPublicBuildsIdRouteImport } from './routes/api/public/builds.$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatchRoute = ApiPatchRouteImport.update({
  id: '/api/patch',
  path: '/api/patch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSelfTestRoute = ApiPublicSelfTestRouteImport.update({
  id: '/api/public/self-test',
  path: '/api/public/self-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildsRoute = ApiPublicBuildsRouteImport.update({
  id: '/api/public/builds',
  path: '/api/public/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildsIdRoute = ApiPublicBuildsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicBuildsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/patch': typeof ApiPatchRoute
  '/api/public/builds': typeof ApiPublicBuildsRouteWithChildren
  '/api/public/self-test': typeof ApiPublicSelfTestRoute
  '/api/public/builds/$id': typeof ApiPublicBuildsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/sitemap.xml'
    | '/unlock'
    | '/api/generate'
    | '/api/health'
    | '/api/patch'
    | '/api/public/builds'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/sitemap.xml'
    | '/unlock'
    | '/api/generate'
    | '/api/health'
    | '/api/patch'
    | '/api/public/builds'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/sitemap.xml'
    | '/unlock'
    | '/api/generate'
    | '/api/health'
    | '/api/patch'
    | '/api/public/builds'
    | '/api/public/self-test'
    | '/api/public/builds/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnlockRoute: typeof UnlockRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPatchRoute: typeof ApiPatchRoute
  ApiPublicBuildsRoute: typeof ApiPublicBuildsRouteWithChildren
  ApiPublicSelfTestRoute: typeof ApiPublicSelfTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patch': {
      id: '/api/patch'
      path: '/api/patch'
      fullPath: '/api/patch'
      preLoaderRoute: typeof ApiPatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/self-test': {
      id: '/api/public/self-test'
      path: '/api/public/self-test'
      fullPath: '/api/public/self-test'
      preLoaderRoute: typeof ApiPublicSelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builds': {
      id: '/api/public/builds'
      path: '/api/public/builds'
      fullPath: '/api/public/builds'
      preLoaderRoute: typeof ApiPublicBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builds/$id': {
      id: '/api/public/builds/$id'
      path: '/$id'
      fullPath: '/api/public/builds/$id'
      preLoaderRoute: typeof ApiPublicBuildsIdRouteImport
      parentRoute: typeof ApiPublicBuildsRoute
    }
  }
}

interface ApiPublicBuildsRouteChildren {
  ApiPublicBuildsIdRoute: typeof ApiPublicBuildsIdRoute
}

const ApiPublicBuildsRouteChildren: ApiPublicBuildsRouteChildren = {
  ApiPublicBuildsIdRoute: ApiPublicBuildsIdRoute,
}

const ApiPublicBuildsRouteWithChildren = ApiPublicBuildsRoute._addFileChildren(
  ApiPublicBuildsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnlockRoute: UnlockRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPatchRoute: ApiPatchRoute,
  ApiPublicBuildsRoute: ApiPublicBuildsRouteWithChildren,
  ApiPublicSelfTestRoute: ApiPublicSelfTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
